### ISSUE TITLE
Can't install Plugin couchbase 4.0  + elasticsearch 2.0

### ISSUE THREAD

**Issue by hoangton** [couchbaselabs/elasticsearch-transport-couchbase#101] opened 2015-11-01 03:07 UTC
./plugin install  http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip

bin]# ./plugin install  http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip
-> Installing from http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip...
Trying http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip ...

Downloading ................................................DONE
Verifying http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip checksums if available ...
Failed: IOException[Server returned HTTP response code: 403 for URL: http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip.sha1]; nested: IOException[Server returned HTTP response code: 403 for URL: http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip.sha1]; 
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by hiteshmahajan** [comment] 2015-11-02 13:25
same issue :(

**Comment by WillGardella** [comment] 2015-11-02 22:24
For those who are experiencing this issue, are you using the plugin with Elasticsearch 2.0? ES 1.7 is the highest supported version number. In ES 2.0 there have been changes to the Elasticsearch plugin architecture.

**Comment by bignolip** [comment] 2015-11-05 23:35
Hi Everyone,

I've been using the CouchBase to ES transport connector with pre-2.x versions of ES for a while and I've spent a good deal of time this week trying to unofficially cobble together a version of the connector that will work with ES 2.0.  

Hopefully, what follows in this comment will be of some use to whoever is working on the official update of the connector.  I am using a Mac for development.

I was able to modify the connector code enough to get it to compile with the 2.0 ES libraries and to get it to install into my local copy of ES 2.0.  However, I could not get ES 2.0 to run with the plugin.

What I am having the most trouble with is that the framework for adding plugins to ES has changed in a way that is causing the CAPIServer project component of the connector to throw an AccessControlException while trying to add a user during the connection process.  Specifically, the missing permission is javax.security.auth.AuthPermission "modifyPrincipals":  

Exception in thread "main" BindHttpException[Failed to bind to [9091-10091]]; nested: AccessControlException[access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")];
Likely root cause: java.security.AccessControlException: access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at javax.security.auth.Subject$SecureSet.add(Subject.java:1110)
	at java.util.Collections$SynchronizedCollection.add(Collections.java:2035)
	at org.eclipse.jetty.security.MappedLoginService.putUser(MappedLoginService.java:185)
	at com.couchbase.capi.CAPIServer.basicAuth(CAPIServer.java:142)
	at com.couchbase.capi.CAPIServer.<init>(CAPIServer.java:74)
	at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1.onPortNumber(CouchbaseCAPITransportImpl.java:202)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:69)
	at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl.doStart(CouchbaseCAPITransportImpl.java:193)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.transport.couchbase.CouchbaseCAPI.doStart(CouchbaseCAPI.java:42)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
	at org.elasticsearch.node.Node.start(Node.java:240)
	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:206)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:272)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

I was not familiar with the whole java security policy suite before working on this, so it took me a while to figure out how to even go about modifying these permissions.  Eventually, I found that I could use a JVM argument to load a custom policy file when starting ES, which can be specified by setting the JAVA_OPTS environment variable that the /bin/elasticsearch script reads (export JAVA_OPTS="-Djava.security.manager -Djava.security.policy=../config/plugins.permissions"). 

In the plugins.permissions file, I originally had:

grant {
  ... // Other permissions 
  permission javax.security.auth.AuthPermission "modifyPrincipals";
};

This fixed the original exception, but caused another one to be thrown:

Exception in thread "main" java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "createSecurityManager")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.<init>(SecurityManager.java:299)
	at org.elasticsearch.bootstrap.Security$1.<init>(Security.java:103)
	at org.elasticsearch.bootstrap.Security.configure(Security.java:103)
	at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:181)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

If you look at the "2.0" branch of the elastic/elasticsearch git repo, you'll see that the code is trying to create a new SecurityManager programmatically, which it then fills with permissions as specified in the ES Environment variable.

I tried adding the following line to my plugins.permissions:
  permission java.lang.RuntimePermission "createSecurityManager";
But the exception was still thrown.

I looked in my system's JAVA_HOME/jre/lib/security/java.security file to see if there was anything in there that overrode the "createSecurityManager" permission, but I couldn't find anything (my system policy/security files all have the default values).

What is interesting is that the latest version of ES (the "2.x" and "master" branches) have the ability for plugins to specify their own addendum to the policy in a predefined "plugin-security.policy" file.  This is not possible in the released version of Elastic 2.0.

If anyone has any insight into this, I would be very grateful.

I am unsure why the connector plugin did not have this permissions issue when working with past versions of ES (I've tried the 2.1 connector with ES 1.6 and 1.7).  Is it possible to massage the permissions somehow that will allow the CAPIServer connection to succeed?

Please let me know if I can provide any additional information or clarifications.

Thanks!

**Comment by bignolip** [comment] 2015-11-06 19:34
Update:

I did a lot of digging around in the Elastic 2.0 branch on Git hub and I found out where in the code the SecurityManager and Policy are being handled.  If you go to "https://github.com/elastic/elasticsearch/tree/2.0/core/src/main/java/org/elasticsearch/bootstrap" you will see two files called ESPolicy.java and Security.java.  ESPolicy loads a security.policy file that is distributed along with the elasticsearch-2.0.0 build (it is located in elasticsearch-2.0.0/lib/elasticsearch2.0.0.jar/org/elasticsearch/bootsrap/security.policy).  I was able to unzip the Jar, modify that file appropriately (see below), rezip it, and then run elasticsearch with my locally updated transport-couchbase plugin installed.

The following permissions had to be added to this file to get ES to run the plugin:

  permission javax.security.auth.AuthPermission "modifyPrincipals";
  permission javax.security.auth.AuthPermission "modifyPrivateCredentials";
  permission javax.security.auth.AuthPermission "setReadOnly";

  permission java.lang.RuntimePermission "setContextClassLoader";

Now, it seems to me that it is a really bad practice to break into the ES distribution and monkey around with the resource files, but I could see no other way to accomplish this in ES 2.0.0 (without modifying any ES code itself).  If you look closely at the ESPolicy and Security classes, you'll see that the only dynamic permissions that can be specified are FilePermissions and I'm not even sure how to specify those.  There appears to be no way to add other kinds of permissions without resorting to adding them to ES's security.policy file.

I tried a number of work-arounds in the plugin code itself, which did not work.  For example, I tried setting the security manager to null in the plugin (System.setSecurityManager(null)), but the "setSecurityManager" permission is (not surprisingly) not granted in the ES policy file.  Trying to wrap the code that actually creates the CAPIServer in a doPriviledged() block was also unsuccessful.  I think that that particular approach failed because the base security policy did not include the "modifyPrincipals" permission.

In light of all this, I would be very interested to see what official solution is possible to get this plugin to work with ES 2.0.0.  Later version of ES seem to allow plugins to specify their own extensions to the ES policy through the "plugin-security.policy" file.

**Comment by bignolip** [comment] 2015-11-06 22:33
Update:

After a lot of setbacks, I have been able to get my locally modified transport script to work with ES 2.0.0.  One issue that I found is that the transport-couchbase connector seems to be sending the "couchbaseCheckpoint" documents to all of the indices on my cluster.  This appears to also be happening on the out-of-the-box connector when used with ES 1.7, so I don't think that I messed anything up to cause that behavior.

These indices also include behind-the-scenes things created for ES plugins (e.g. .marvel-2015.11.06).  While this does not seem to cause any issue on ES 1.7, in ES 2.0, at least the .marvel* indices do not support dynamic mappings, so the connector causes an exception to be thrown when trying to connect to ES if the marvel plugin is installed.

I just deleted the .marvel* indices from my local ES and the connector was able to connect to my ES 2.0 instance and transfer documents.

**Comment by bignolip** [comment] 2015-11-06 22:39
Update:

One final thing.  The ElasticSearchCouchbaseBehavior class assumes that the "published host" address will be in IPv6 format.  I'm not sure if there is a way to force ES to use IPv6 over IPv4, but with ES 2.0, the default format of the address returned by calling resolvePublishHostAddress(...) was IPv4 on my system.  This broke the parsing code in the ElasticSearchCouchbaseBehavior.getNodesServingPool(...) method.  Specifically, that in IPv4 addresses, there are no ']' characters, so the end boundary of the hostPort substring was coming out to be -1.  I locally added a condition that changed the end boundary to the length of the address string if there were no ']''s in the address string.

**Comment by Branor** [comment] 2015-11-08 08:25
@bignolip That was an amazing amount of research done, thank you. I'll add a proper plugin-security.policy to the plugin so it will actually work with ES 2.x, and also see if I can get it to work with 2.0. 

Would you like to merge your changes in?

**Comment by bignolip** [comment] 2015-11-09 16:46
@Branor 

Sure, I can add my changes.  Happy to help--this project has been really helpful!  Should I create a new branch and issue a pull request?  I'm not sure what your process is with this project.  Thanks!

Also, I'm not sure that my changes regarding the new InetAddress interface are correct.  I just did what I needed to get the connector to work with the new version.  This seemed to cause the addresses to go from an IPv6 to an IPv4 format.  Is trying to get them back in IPv6 format desired?  Thanks!

**Comment by android-programmer** [comment] 2015-11-10 05:37
+1

**Comment by chenbekor** [comment] 2015-11-10 05:55
+1

**Comment by arthurgimpel** [comment] 2015-11-15 09:55
+1

**Comment by bignolip** [comment] 2015-11-16 16:28
I would be happy to upload my modifications, but I don't have permission to contribute to the project.  If there is another way that I can share my changes, please let me know.  Thanks!

**Comment by WillGardella** [comment] 2015-11-17 01:46
@bignolip I just noticed that the normal page that describes how to contribute (http://developer.couchbase.com/open-source-projects) doesn't cover any of the connectors. I've asked internally. It may take a few days to get a response so hopefully @Branor gets back to you faster than that.

**Comment by bignolip** [comment] 2015-11-17 17:32
@WillGardella Thanks!  I'd be happy to contribute!

**Comment by Branor** [comment] 2015-11-17 21:34
@bignolip The simplest way would be to fork the github repo, add your changes, and then submit a pull request, so I'll be able to merge your changes in. (https://github.com/couchbaselabs/elasticsearch-transport-couchbase/pulls)

**Comment by bignolip** [comment] 2015-11-19 00:36
@Branor Sorry for the delay.  I discovered that there is going to have to be different versions for 2.0 and 2.x due to small changes in the ES library.  I was working on getting a 2.x version ready, but ran into the newly introduced "jar hell" check the ES folks put in 2.x.  It took me a long time to figure out what was causing the issue (to my embarrassment).  I got it sorted out and I will create a new pull request for the 2.x code, since that one will work out-of-the-box.

**Comment by bignolip** [comment] 2015-11-19 22:26
@WillGardella @Branor 
My PR (#104) is ready for review.  This should enable the plugin to be used with the 2.x branch of the ES repo:  https://github.com/elastic/elasticsearch/tree/2.x

**Comment by Branor** [comment] 2015-11-24 13:12
@bignolip thanks! I had a couple of questions about the RP, could you please take a look at the inline comments there?

**Comment by Branor** [comment] 2015-11-24 13:20
BTW, regarding indexes that start with a dot (like ".marvel", etc) - I've pushed out a small fix version that addresses this. The plugin will now ignore all dot-indexes by default, and you can also specify a white-list of index names in the config file, to cause the plugin to ignore ALL other indexes. 

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.2

Note that this doesn't affect the template, just the plugin trying to write replication checkpoints to all indexes.

**Comment by bignolip** [comment] 2015-11-24 18:22
@Branor Okay, thanks!  I'll merge those changes into my PR once we get the other issues straightened out.  I think that I've now addressed all of the comments that were made so far.

**Comment by bignolip** [comment] 2015-11-24 19:21
@Branor Also, I've done more research into how to get this to work for ES 2.0.  I've looked through the Security/Bootstrap/Environment/ESPolicy in more detail and I *think* that the only ways to get around the Java Security Permission issues (without actually changing ES code and rebuilding) are:

1.)  Disabling the Security Manager in ES all together:
      SecurityManager can be disabled completely with this setting:
            es.security.manager.enabled = false

2.)  Manually unzipping the ES 2.0.0 release jar and editing the security.policy resource file directly (as I outlined in a comment further up in this discussion).

3.)  Creating a "dummy jar" that contains a security.policy file in the same path as the security.policy file that is loaded up ES on start up.  If the classpath parameter passed to the JVM when running ES (see the %ES_HOME%/bin/elasticsearch file) is changed so that the path to the dummy jar is listed before the path to the default ES_CLASSPATH (the %ES_HOME%/lib directory I think, at least on Mac), then org.elasticsearch.bootstrap.ESPolicy.java will be loaded instead of the security.policy file provided in the ES distribution. 

To get this to work, the calls to run ES would be changed in ./bin/elasticsearch from:

    if [ -z "$daemonized" ] ; then
        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp   "$ES_CLASSPATH" \
          org.elasticsearch.bootstrap.Elasticsearch start "$@"
    else
        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" \
          org.elasticsearch.bootstrap.Elasticsearch start "$@" <&- &
    fi

to:

    if [ -z "$daemonized" ] ; then
        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$OVERRIDING_JAR_PATH:$ES_CLASSPATH" \
          org.elasticsearch.bootstrap.Elasticsearch start "$@"
    else
        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "OVERRIDING_JAR_PATH:$ES_CLASSPATH" \
          org.elasticsearch.bootstrap.Elasticsearch start "$@" <&- &
    fi

Please let me know if you have any questions about this and whether or not you would like to create an ES 2.0 version of this PR with one of the workarounds listed above.  Also, if you can think of other ways to get around the Java Security Permissions in 2.0, I'd be very interested to know.  Thanks!

**Comment by WillGardella** [comment] 2015-11-24 19:46
It appears that ES 2.1 was released this morning:
https://www.elastic.co/blog/elasticsearch-2-1-0-and-2-0-1-released

I don't think it's necessarily a good idea to add a lot of complexity or
disable security to support ES 2.0 - do you still feel it's necessary?

**Comment by bignolip** [comment] 2015-11-25 00:09
@WillGardella Okay, thanks for the heads up!  The ES people really made the security a pain in 2.0!    Looking at 2.1, the ESPolicy class now is at least able to merge in permissions from the System security policy, which is defined in: %JAVA_HOME%/lib/security/java.policy

I think that it *should* be easy enough to adapt the changes for 2.x to be compatible with 2.1, which would then only require users to edit the permissions in their java.policy file.  I'm not sure when ES 2.2 is coming out.  That is the first version that *should* be compatible with my PR for ES 2.x.

I'm not sure about compatibility with 2.0.1, because I'm not sure what branch in the Git code base that is being built from...  I'll whip that up after I finish getting my current PR in order.

**Comment by bignolip** [comment] 2015-11-25 01:39
@Branor I just updated my PR to merge in your recent changes to master and to reflect the changes in setting the TypeSelector, etc.

**Comment by bignolip** [comment] 2015-11-25 18:42
@Branor @WillGardella FYI, I just made a quick PR for an ES 2.1.0-compatible transport.  Both of my PRs are going into Master now, but maybe there should be different branches for each of these, since they are compatible only with the version of ES for which they were developed (due to changes in the ES libraries).

**Comment by PaulCapestany** [comment] 2015-12-05 09:53
+1

**Comment by rmuir** [comment] 2015-12-07 01:10
@bignolip I am sorry for all the pain you faced here: I think most of it is my fault.

Just to confirm some questions (I think you already correctly understood the situation):
* for 2.0, the only thing you can do is hack the resource files, security is not configurable.
* for 2.1, system policy mechanism is respected (configuration files and commandline flag -Djava.security.policy)
* for 2.2, in addition, plugins can request additional permissions granted only to them.

BTW it was not intentional to make things painful, just a matter of hours in the day, being cautious, and huge codebase to try to secure.

**Comment by bignolip** [comment] 2015-12-07 18:43
@rmuir 
No need for apologies!  I learned a lot while investigating this.  I am happy to confirm that my findings align completely with your breakdown per ES version given above.  ElasticSearch has been a great tool for getting search up and running at my organization.

**Comment by PaulCapestany** [comment] 2015-12-08 02:36
@bignolip just wanted to thank you for all your comments/fixes—I can confirm that I was able to build from your fork and finally got Couchbase 4.1 (DP) and Elasticsearch 2.1 working nicely together :)

**Comment by Branor** [comment] 2015-12-30 16:47
Just released the updated plugin versions for ES 2.1.0 and ES 2.1.1. Unfortunately, the way plugins in ES now work means that they are exactly version specific, so there are separate releases of the plugin for every release of ES:
ES 2.1.1: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.2.1
ES 2.1.0: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.2.0

**Closed by Branor** 2015-12-30 16:47 UTC
Labels: enhancement

**Comment by hiteshmahajan** [comment] 2016-01-05 08:03
@Branor :+1:

**Comment by bigShai** [comment] 2016-01-24 15:11
Hi @Branor,
I downloaded the latest transport version + changed the security file. 
Still getting the same error.
Any advice?
