### ISSUE TITLE
Ignore certain documents for replication based on _id type

### ISSUE THREAD

**Issue by rajeshetty** [couchbaselabs/elasticsearch-transport-couchbase#61] opened 2015-01-08 22:49 UTC
I know this question has been asked in different forms ,but not sure if there is resolution to this or not..

Requirement is to simply ignore
* All documents that are NOT mentioned/match in elasticsearch.yml mapping (couchbase.documentTypes.XXXX mapping)
*   key /value lookup 

because I do see following error in the ES log 

[2015-01-08 10:47:22,758][ERROR][transport.couchbase.capi ] [Tigra] Body was:  Parse error was: java.io.EOFException: No content to map to Object due to end of input
[2015-01-08 10:47:22,761][ERROR][transport.couchbase.capi ] [Tigra] Unable to parse decoded base64 data as JSON, indexing stub for id: question-9

where as I actually want to ignore question-X type of documents from replicating.

So the question
* Is there any way to tell CB or ES to not to index them , if yes how ? (Any regEx ?)
* If there is no way to do this, Where do they end up in ES by default  and is there any way to change this default type , to send all the documents that we don't care about can go in one big index type of UNWANTED?

**Comment by mschoch** [comment] 2015-01-08 22:58
1.  There is currently no way to prevent Couchbase from sending these mutations.
2.  To the best of my knowledge there is no way to have Elasticsearch completely ignore the documents.  The best you could do is use a regex to map these to a type, say UNWANTED, and configure that type to not store or index any fields.

The message you see above is expected when the document is not JSON.  Its unfortunate because if you have a lot of non-JSON documents the message is a nuisance.  However, if you expect to have all valid JSON documents, then its a valuable debugging mechanism.

There is also a bug in the current released version in which deleted documents also display this message .

I think there are 2 possible action items here:

1.  Change the log level of the message above.  It is not an error and should not be logged as such.  It should be changed to either INFO or DEBUG.
2.  We could add a feature to the plugin to ignore documents matching a regex.  This should not be that hard to support.

**Comment by rajeshetty** [comment] 2015-01-09 01:32
I like your recommendation about adding a feature in the transport plugin ; way to specify regex to ignore certain documents based on their Id prefix . Providing a list in this regEx would be even helpful . that way you can ignore list of document types.  When do you think we can get it in ?

Going back to the error. Actually following error that I'm seeing in the ES as it complains that it is not a JSON. BUT IT IS. Its a valid JSON doc. just that its not configured in elasticsearch.yml to go to any index types. 

Unable to parse decoded base64 data as JSON, indexing stub for id: question-9

So first question why am I seeing this error even if its a valid JSON doc?

**Comment by mschoch** [comment] 2015-01-09 01:38
I'm not actually the maintainer of this any more, so I can't make any comment about how fast this change might get incorporated.

Regarding the error message, the only known reason you would see this for document containing valid JSON is if you deleted it.  That too was a bug, that has been fixed, but not released.

**Comment by Branor** [comment] 2015-01-09 18:46
Hi there!

I'm taking over maintaining the plugin at the moment. I actually already coded this exact feature, just need to get it merged into the master branch. You'll be able to both filter documents (on the ES side) by regex and, optionally, also wrap non-JSON objects in a JSON document if you want them stored in ES after all.

**Comment by rajeshetty** [comment] 2015-01-09 18:48
very cool. Any idea when will this plugin be officially released ?.

**Comment by Branor** [comment] 2015-01-10 08:26
It will be at least another couple of weeks. However if you want to try it out right now, you can clone my forked branch and build a version of the plugin for yourself: https://github.com/Branor/elasticsearch-transport-couchbase

To wrap non-JSON values in a document on the ES side, add this to your elasticsearch.yml config file:
couchbase.wrapCounters: true

To use the regex key filter add:
couchbase.keyFilter: org.elasticsearch.transport.couchbase.capi.RegexKeyFilter
couchbase.keyFilterType: [exclude|include]
couchbase.keyFilters.filter1: <regex>
couchbase.keyFilters.filter2: <regex>

The keyFilterType setting determines how the plugin treats the document IDs that match the specified filters: "exclude" (default) means it will store all documents except the ones that match the regex; "include" means it will only store the documents that match the regex. The name of the filters (filter1, filter2) is arbitrary and has no functional purpose other than to let you name them in the config file, so you remember what it was stupposed to be 6 months from now. :)

**Comment by chenbekor** [comment] 2015-01-11 06:48
hey David - nice to e-meet you. it is really great news to hear that couchbase are continuing to support the ES plugin. I wish you Good Luck with your new role at Couchbase!

to this specific ticket - may I ask to add the above functionality on a per index settings?

this will help us to add filter in / out on a per index level. would be great if index name could also  be a RegEx.

thank you!

**Comment by rajeshetty** [comment] 2015-01-24 05:48
HI  David,

Is the above filter , exclude/include ready to be downloaded and used yet ?.

BTW, 
> I still did not get how filters work with specific type of document ids or lookup types.

e.g lets say I want to exclude any document id's that match following regEx : ^abc:.*$ , ^xyz:.*$   etc

will this take care of any doc id's , whether the value is a simple string or JSON doc ?

> How are you supposed to wrap simple key/ value into json doc before sending to ES ? - example would help.

-Thanks
Rajesh

**Comment by Branor** [comment] 2015-01-27 09:09
Hi folks,

I'll look into adding the filter and type selectors on a per-index basis, it just requires some more work.

The filter has two modes: exclusive or inclusive. In exclusive mode, it excludes any document IDs that match any of the filter expressions. So in your example, this would be the right thing to use. In inclusive mode, it excludes all OTHER documents, and only lets the documents that match one of the filter expressions pass through. The filter doesn't look at the doc value, it only works on the ID. (There's a feature request to also have a filter based on values, but I'm thinking how to implement it because it can have major performance implications if I start examining all documents.)

The wrapping feature is very simple - the plugin tries to decode the document value as a JSON string, if it doesn't manage it tries to parse it as a long. If the value is indeed a long, the plugin indexes it as a document with the following format: { "value" : <long value> }  - it keeps the same document ID.

**Comment by rajeshetty** [comment] 2015-01-27 19:11
> In your example above looks like you can either do exclude or include for all the documents right, you can do both can you?. because the way I understand is

couchbase.keyFilterType: [exclude|include]
couchbase.keyFilters.filter1: regex
couchbase.keyFilters.filter2: regex

Basically filter1, filter2 will use filterType specified above for (exclude or include) - Makes more sense to do include, which means Only use filter1..n specified in include fashion and ignore all other document id's 

e.g.

couchbase.keyFilterType: include
couchbase.keyFilters.filter1: ^s:.*$
couchbase.keyFilters.filter2: ^ssm:.*$
couchbase.keyFilters.filter3: ^u:.*$

which means that only index documents matching ^s:.*$, ^ssm:.*$,  ^u:.*$ and ignore all other documents. 

Can you confirm ?

Also which means that we still need couchbase.typeSelector: org.elasticsearch.transport.couchbase.capi.RegexTypeSelector since thats the config which tells ES , how to index each of those ids. Right ?


BTW, is it ready to be downloaded officially as a plugin or still being worked on ?

-Thanks
Rajesh

**Comment by ltamrazov** [comment] 2015-02-11 20:14
Hello, 

We downloaded your branch with this feature and we get the following error when launching elastic:   
 
    {1.3.2}: Initialization Failed 
    1) NullPointerException[null]

We took a look at the latest merge pull request from talma/master (message: Support group type regex and parent indexing, d3605f8958e7722c462b3940b2cb76300b1bda37) and found that including this class in the yml file fixes the issue:

    couchbase.parentSelector: org.elasticsearch.transport.couchbase.capi.RegexParentSelector
 
The problem is in DefaultParentSelector.java line 24 - 26:

    if (documentTypeParentFields.isEmpty()) {
        documentTypeParentFields = null;
    }

Commenting these out resolved the issue. There also appears to be a repetition on lines 40 - 42:

    if(documentTypeParentFields != null && documentTypeParentFields.containsKey(type)) {
        parentField = documentTypeParentFields.get(type);
    }

This code was repeated just above those lines. We'll create a pull request for this. 

Thanks,

**Comment by rajeshetty** [comment] 2015-02-11 21:29
is this available now and official yet ?

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/pull/68#event-234240603

**Comment by Branor** [comment] 2015-02-13 19:00
You can get a test build of all the new stuff in the plugin here: https://drone.io/github.com/Branor/elasticsearch-transport-couchbase/files/target/releases/elasticsearch-transport-couchbase-2.1.0-SNAPSHOT.zip
An updated readme with all the configuration options: https://github.com/Branor/elasticsearch-transport-couchbase/blob/master/README.md

It's currently in QA, and will be released Real Soon (TM).

**Comment by sandeepjainHSC** [comment] 2015-04-14 07:44
Hi Branor.

Is  This Filtering featured has been added to all the version of Plugins ?

**Comment by Branor** [comment] 2015-06-02 15:48
Feature is added in v2.1.1, RC here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC

**Closed by Branor** 2015-06-02 15:48 UTC

**Comment by GirishGandhi** [comment] 2016-06-29 10:33
HI Team,

Actually i want to enable Advanced Filtering in Couchbase and want to exclude documents containing _sync:rev in Id Could you please explain the steps or Give me any example how to enable Advanced filtering in Couchbase. 
Thanks in Advance.
